# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish

# File Options
files:
  include: '**/*.s+(a|c)ss'

# Rule Configuration
rules:
  border-zero:
    - 1
    -
      convention: none
  brace-style:
    - 2
    -
      style: 1tbs
      alllow-single-line: false
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - alphabetical
  variable-for-property:
    - 2
    -
      properties:
        - color
